/*
 * Represents all fingers of both hands
 */
const FINGERS = {
  // None
  NONE: 'FINGERS.NONE',
  // Left
  LEFT_THUMB: 'FINGERS.LEFT_THUMB',
  LEFT_INDEX: 'FINGERS.LEFT_INDEX',
  LEFT_MIDDLE: 'FINGERS.LEFT_MIDDLE',
  LEFT_RING: 'FINGERS.LEFT_RING',
  LEFT_LITTLE: 'FINGERS.LEFT_LITTLE',
  // Right
  RIGHT_THUMB: 'FINGERS.RIGHT_THUMB',
  RIGHT_INDEX: 'FINGERS.RIGHT_INDEX',
  RIGHT_MIDDLE: 'FINGERS.RIGHT_MIDDLE',
  RIGHT_RING: 'FINGERS.RIGHT_RING',
  RIGHT_LITTLE: 'FINGERS.RIGHT_LITTLE'
}

export default FINGERS
